"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const delauney_1 = require("./delauney");
const quadedge_1 = require("./quadedge");
let a = new quadedge_1.vertex(-10000, 0);
let b = new quadedge_1.vertex(10000, 0);
let c = new quadedge_1.vertex(0, 10000);
let dt = new delauney_1.triangulation(a, b, c);
dt.list_edges();
dt.insert_point(new quadedge_1.vertex(1000, 200));
dt.list_edges();
dt.insert_point(new quadedge_1.vertex(100, 190));
dt.list_edges();
